services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ecommerce  
      POSTGRES_PASSWORD: ecommerce  # Real system should not store sensitive info in source like this
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  observability:
    image: grafana/otel-lgtm:latest
    ports:
      - "3005:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  edge-api:
    build:
      context: ./services/edge-api
      dockerfile: Dockerfile
      target: runner-dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://ecommerce:ecommerce@postgres:5432/ecommerce
      OTEL_SERVICE_NAME: edge-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://observability:4318
    depends_on:
      postgres:
        condition: service_healthy
      observability:
        condition: service_started

  inventory:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
      target: runner-dev
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ecommerce
      DATABASE_USER: ecommerce
      DATABASE_PASSWORD: ecommerce # Real system should not store sensitive info in source like this
      OTEL_SERVICE_NAME: inventory-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://observability:4318
    depends_on:
      postgres:
        condition: service_healthy
      observability:
        condition: service_started

  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
      target: runner-dev
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://observability:4318
    depends_on:
      observability:
        condition: service_started

  order:
    build:
      context: ./services/orders
      dockerfile: Dockerfile
      target: runner-dev
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ecommerce
      DATABASE_USER: ecommerce
      DATABASE_PASSWORD: ecommerce # Real system should not store sensitive info in source like this
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://observability:4318
    depends_on:
      postgres:
        condition: service_healthy
      observability:
        condition: service_started

volumes:
  postgres_data:
